### ISSUE TITLE
Maya: Look collect textures for Hero version

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3263] opened 2022-05-30 11:32 UTC
**Describe the bug**

The current implementation of Hero versions for Looks is a bit questionable.

We are copying all texture to hero/resources folder but shaders in hero folder are linked against versioned shaders of the look (different folder).

so we are creating unnecessary duplications which are not used anywhere. With specific assets we can have gigabytes of data copied unnecessarily. 

**To Reproduce**

publish look with hero versions enabled

![image](https://user-images.githubusercontent.com/352795/170983402-a2e87526-f2c2-401c-a2b1-392b3323ebf7.png)

**Expected behavior**

- we should either stop copying textures to hero folder (they are not used anyway)
or
- we should repath textures in hero version shaders to use these textures

[cuID:2eqzt1y]

**Comment by BigRoy** [comment] 2022-05-30 12:20
Is this a duplicate of this issue: https://github.com/pypeclub/OpenPype/issues/3213
It feels like almost a 1-to-1 correspondence.

**Comment by m-u-r-p-h-y** [comment] 2022-05-30 13:28
You are absolutely right. I'm getting older and forgetting more and more . . .   :)

closing this one

thank you!

**Closed** 2022-06-07 20:41 UTC
Labels: host: Maya
