### ISSUE TITLE
Nuke 13.2v1 compatibility

### ISSUE THREAD

**Issue by NickPittas** [pypeclub/OpenPype#3334] opened 2022-06-13 21:45 UTC
Updating to the latest version in 2 different Windows installations, seem to make the Nuke 13 app to disappear from the launcher.
Nuke 12 is there instead. 
No custom environment vars anywhere and the settings have the updated path for Nuke 13.2v1

[cuID:2ff02dh]

**Comment by jakubjezek001** [comment] 2022-10-13 08:37
We could not replicate the issue. It seems it is caused by Settings versioning. Lots of changes / improvements had been done in the field since June. 

Try to replicate it now @NickPittas but I am closing the issue for now. Please, reopen the issue in case it is still happening.

**Closed by jakubjezek001** 2022-10-13 08:37 UTC
