### ISSUE TITLE
Nuke: deep image exr loading

### ISSUE THREAD

**Issue by jakubjezek001** [pypeclub/OpenPype#4106] opened 2022-11-18 13:05 UTC
**Is your feature request related to a problem? Please describe.**
Deep image ex can occasionally be used in productions and we do not support loading them yet. 

**Describe the solution you'd like**
- enhancing actual LoadClip plugin
- find some way how to identify exr in representation as deep images - OIIO can read metadata and flag it during publishing into version and save it into representation.data. So during loading this flag will tell the plugin to chose different Read node.
- if deep image representation is identified then use DeepRead node.
- rest is the same as normal Read node. 

[cuID:33a7exa]

**Comment by antirotor** [comment] 2022-11-23 17:37
@jakubjezek001 duplicate of #4107 , reopened by some reason by pypebot?

**Closed by antirotor** 2022-11-23 17:37 UTC
