### ISSUE TITLE
Maya: Validate Frame Range repair will fail for Renderlayers

### ISSUE THREAD

**Issue by BigRoy** [pypeclub/OpenPype#2662] opened 2022-02-04 18:38 UTC
**Describe the bug**

The Maya Validate Frame Range function has a [repair method that updates the instance `frameStart` and `frameEnd`](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/validate_frame_range.py#L82-L93). However, Renderlayers do not have that setting on the instance and thus will error.

```python
plugin is: <class 'S:\openpype\OpenPype\openpype\hosts\maya\plugins\publish\validate_frame_range.py.ValidateFrameRange'>
Preparing <class 'openpype.action.RepairAction'>..
Action prepared.
// pyblish.pyblish.plugin.Action : Finding failed instances..
// Error: pyblish.plugin : Traceback (most recent call last):
  File "S:\openpype\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "S:\openpype\OpenPype\openpype\action.py", line 65, in process
    plugin.repair(instance)
  File "S:\openpype\OpenPype\openpype\hosts\maya\plugins\publish\validate_frame_range.py", line 90, in repair
RuntimeError: setAttr: No object matches name: Main.frameStart

Traceback (most recent call last):
  File "S:\openpype\OpenPype\.venv\lib\site-packages\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "S:\openpype\OpenPype\openpype\action.py", line 65, in process
    plugin.repair(instance)
  File "<string>", line 90, in repair
RuntimeError: setAttr: No object matches name: Main.frameStart
 // 
```

[cuID:24ve6vj]

**Comment by m-u-r-p-h-y** [comment] 2022-10-06 07:09
closing as a duplicate of #3302

**Closed by m-u-r-p-h-y** 2022-10-06 07:09 UTC
