### ISSUE TITLE
Maya: Camera Overscan Attribute

### ISSUE THREAD

**Issue by tokejepsen** [pypeclub/OpenPype#2807] opened 2022-02-24 14:40 UTC
**Describe the bug**
When animating camera attributes and publishing a camera alembic, then referencing this back into Maya, it'll connect all camera attributes to the alembic node. Regardless of whether the attribute were animated in the first place.

**To Reproduce**
1. Animated camera scale attribute.
2. Publish camera.
3. Load camera.
4. Publish review with the loaded camera.
5. Error on Playblast extraction because overscan attribute is connected to the alembic node.

**Expected behavior**
The overscan attribute is rarely (is ever) animated, so a solution would be to disconnect the overscan attribute when loading the camera.
Also might be useful to have a validator to check whether the attribute is connected or even locked, because else it'll just error the extraction.

**Comment by BigRoy** [comment] 2022-02-24 14:56
> To Reproduce -> 1) Animated camera scale attribute.

You mean `overscan` attribute. Yes?

> When animating camera attributes and publishing a camera alembic, then referencing this back into Maya, it'll connect all camera attributes to the alembic node. **Regardless of whether the attribute were animated in the first place.**

Is that so? If I extract a camera here it'll only ever connect the keyed attributes (or attributes with input connection).

Tested in Maya 2022 and Maya 2020. It even skips connections to e.g. Scale and Visibility attributes if those were completely static keys on export.

> Error on Playblast extraction because overscan attribute is connected to the alembic node.

Would it potentially make more sense to fix this issue.
Instead of "relying" on setting the value we could also potentially do this during the context of playblasting:

1. Mute the attribute
2. Set the value explicitly to the value we need it to be.

That is, if we're only really ever trying to the fix the playblast/review error.

**Comment by tokejepsen** [comment] 2022-02-24 15:53
> You mean overscan attribute. Yes?

Actually no. I'm mean `scale`. This is to show that animating a different camera attribute, will still connect the `scale` attribute on the loaded camera even though its not animated.

> Tested in Maya 2022 and Maya 2020. It even skips connections to e.g. Scale and Visibility attributes if those were completely static keys on export.

Hmm, cant replicate that here. Original issue was in 2019, but tested 2022 and still getting the same issue when going through the reproduction steps.

> Mute the attribute - with the API likely more trivial to "force disconnect temporarily"

That might be the way to go. Compensate in the extraction cause that is the "only" place its an issue.

**Comment by m-u-r-p-h-y** [comment] 2022-06-20 09:41
I'm also not able to reproduce this behavior


- animate camera scale and other transforms
- publish the camera
- new scene
- load the camera as abc

only the animated channels are connected, alembic is smart and skips static keys and leaves the channels free (not animated)
other camera attributes are not touched at all

![image](https://user-images.githubusercontent.com/352795/174573197-76719047-9b0d-4789-8839-6b2babea0f32.png)



when the same camera is loaded as MA it is quite different and some shape attributes are keyed, even though they are static.
but overscan is untouched.

![image](https://user-images.githubusercontent.com/352795/174573627-718208bb-2de0-4b7a-99df-53617d3b0400.png)

**Comment by antirotor** [comment] 2022-06-22 14:45
Best approach would be like this:

add to Playblast extractor option to ☑️ *enable overriding of connected attributes*.

If not enabled, applying preset values to locked/connected attributes will soft-fail (with warning).
If enabled, it will temporarily disconnect/unlock, apply value, restore value/lock.

**Comment by BigRoy** [comment] 2022-06-23 13:05
> If not enabled, applying preset values to locked/connected attributes will soft-fail (with warning).
> If enabled, it will temporarily disconnect/unlock, apply value, restore value/lock.

Yes, and possibly even implement that logic in `capture.py` itself so it's automatically fixed in multiple areas where it might get used by OP.

**Comment by antirotor** [comment] 2022-07-15 17:01
#3523 is now addressing the soft-fail nature because it is now production breaking. We still need to do it properly later on.

**Closed** 2022-07-26 08:25 UTC
Labels: host: Maya
